// Cross-codec compatibility layer-1 — S2C fixture verifier (Java → Dart).
//
// ══════════════════════════════════════════════════════════════════════════════
// PURPOSE & CONTRACT
// ══════════════════════════════════════════════════════════════════════════════
//
// This file reads `.cbor` fixtures from `.private.local/vhrp_fixtures/s2c/`
// (produced by the Java-side `VhrpS2cFixtureGenTest.java`) and decodes them
// with Dart's [VhrpCborCodec.decode()], asserting field values against the
// companion `.json` expectation files.
//
// ── Interoperability contracts guarded here ──────────────────────────────────
// C1. Binary payloads (assistant.audio.chunk pcm) encoded by Java as CBOR
//     `bstr` must be decoded by Dart's CborBytes extractor — NOT mistaken for
//     a base64 tstr.  If Java accidentally encoded pcm as base64, the Dart
//     decoder would surface an empty Uint8List and the user would hear silence.
// C2. Text strings encoded by Java as CBOR `tstr` must be decoded as Dart
//     Strings via CborString — not mangled by type mismatch.
// C3. Nested capability extensions map in session.ready must be decoded by
//     Dart correctly so the adapter knows which provider features are
//     available.
// C4. Large integers (contentIndex, sampleCounts) encoded by Java as CBOR int
//     must be decoded by Dart via CborInt.toInt() without overflow.
// C5. Optional nullable fields (replyTo, conversationId, clientItemId) absent
//     from the Java-encoded CBOR map must surface as null in Dart — not throw.
// C6. Non-ASCII Unicode text (Japanese thread content) encoded by Java as
//     CBOR UTF-8 tstr must survive to Dart as ungarbled String.
// C7. Boolean fields (accepted, applied, isSpeaking, recoverable) encoded by
//     Java as CBOR bool must be decoded by Dart as Dart bool — not as int 0/1.
//
// ── skip strategy ────────────────────────────────────────────────────────────
// Java-side fixtures are generated by a separate Gradle test task and committed
// to `.private.local/vhrp_fixtures/s2c/`.  Until the Java generator has run,
// the fixture files do not exist.  Each test in this file uses [_skipIfAbsent]
// to:
//   1. Check whether the `.cbor` file for this fixture exists.
//   2. If absent  → print a prominent skip message and call
//      `markTestSkipped(reason)`.  The test runner reports it as SKIPPED (not
//      FAILED), so the overall suite stays green.
//   3. If present → decode and assert normally.
//
// This means `flutter test` on a clean checkout passes (all S2C tests skip),
// and after `./gradlew test` on the server side has generated S2C fixtures,
// re-running `flutter test` turns all skips to passes (or shows real failures
// if the codecs are incompatible).
//
// ── fixture format expected ───────────────────────────────────────────────────
// Same format as c2s (produced by the Java side):
//   • <name>.cbor — raw CBOR binary produced by Java VhrpCborCodec.encode()
//   • <name>.json — companion expected-value JSON
//     - bstr fields expressed as lowercase hex strings
//     - `"_bstr_encoding": "hex"` and `"_bstr_fields": [...]` keys
//
// ── path resolution ───────────────────────────────────────────────────────────
// `flutter test` CWD == `client/` package root.
// s2c fixture dir: `../.private.local/vhrp_fixtures/s2c/`
//
// ══════════════════════════════════════════════════════════════════════════════

// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:vagina/feat/call/services/realtime/hosted/vhrp_cbor_codec.dart';
import 'package:vagina/feat/call/services/realtime/hosted/vhrp_messages.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Shared helpers
// ─────────────────────────────────────────────────────────────────────────────

const _codec = VhrpCborCodec();

// Path resolution: `flutter test` CWD == `client/` package root.
final _fixtureDir = Directory('../.private.local/vhrp_fixtures/s2c');

/// Reads a fixture pair for [name].
///
/// Returns `(cborBytes, expectedJson)` if both files exist, or null if the
/// .cbor file is absent (Java generator has not run yet).
///
/// The companion .json meta file is required when the .cbor exists; its
/// absence is treated as a test failure (the generator is broken).
({Uint8List cbor, Map<String, dynamic> expected})? _loadFixture(String name) {
  final cborFile = File('${_fixtureDir.path}/$name.cbor');
  if (!cborFile.existsSync()) {
    return null;
  }
  final jsonFile = File('${_fixtureDir.path}/$name.json');
  if (!jsonFile.existsSync()) {
    fail(
      'Fixture $name.json is missing although $name.cbor exists. '
      'The Java generator must output both files.',
    );
  }
  final cborBytes = cborFile.readAsBytesSync();
  final expected =
      jsonDecode(jsonFile.readAsStringSync()) as Map<String, dynamic>;
  return (cbor: Uint8List.fromList(cborBytes), expected: expected);
}

/// Decodes bytes from lowercase hex string [hex].
Uint8List _fromHex(String hex) {
  final result = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < result.length; i++) {
    result[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return result;
}

/// Helper to parse a bstr field from the JSON expectation.
/// Returns raw bytes from the hex-encoded string.
Uint8List _expectedBstr(Map<String, dynamic> expected, String dotPath) {
  final parts = dotPath.split('.');
  dynamic cur = expected;
  for (final part in parts) {
    cur = (cur as Map<String, dynamic>)[part];
  }
  return _fromHex(cur as String);
}

// ─────────────────────────────────────────────────────────────────────────────
// Test entry point
// ─────────────────────────────────────────────────────────────────────────────

void main() {
  setUpAll(() {
    print('[s2c_fixture_verify] fixture dir: ${_fixtureDir.absolute.path}');
    if (!_fixtureDir.existsSync()) {
      print(
        '[s2c_fixture_verify] WARNING: s2c fixture directory does not exist. '
        'All tests in this file will be SKIPPED. '
        'Run `cd server && ./gradlew test` to generate S2C fixtures.',
      );
    }
  });

  // ── session.ready ───────────────────────────────────────────────────────────

  group('S2C: session.ready', () {
    test(
      // Contract C2/C3/C5/C7: sessionId, threadId are tstr; conversationId
      // optional tstr; capabilities.extensions is a list of tstr; replyTo
      // optional tstr.  If Java omits a field or encodes it with the wrong
      // type the Dart decoder silently returns null or throws, breaking the
      // session bootstrap.
      'session_ready__full — sessionId, threadId, conversationId, extensions, replyTo',
      () {
        final f = _loadFixture('session_ready__full');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture session_ready__full.cbor not yet generated. '
            'Run `cd server && ./gradlew test` to produce it.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<SessionReadyMsg>());
        final ready = msg as SessionReadyMsg;

        final body = f.expected['body'] as Map<String, dynamic>;
        expect(ready.sessionId, body['sessionId']);
        expect(ready.threadId, body['threadId']);
        if (body.containsKey('conversationId')) {
          expect(ready.conversationId, body['conversationId']);
        }
        final exts =
            (body['capabilities'] as Map<String, dynamic>)['extensions']
                as List<dynamic>;
        expect(ready.capabilityExtensions, containsAll(exts.cast<String>()));
        if (f.expected.containsKey('replyTo')) {
          expect(ready.replyTo, f.expected['replyTo']);
        }
      },
    );

    test(
      // Contract C5: conversationId and extensions can be absent or empty.
      'session_ready__minimal — no conversationId, empty extensions',
      () {
        final f = _loadFixture('session_ready__minimal');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture session_ready__minimal.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<SessionReadyMsg>());
        final ready = msg as SessionReadyMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(ready.sessionId, body['sessionId']);
        expect(ready.threadId, body['threadId']);
        expect(ready.conversationId, isNull);
        expect(ready.capabilityExtensions, isEmpty);
      },
    );
  });

  // ── session.resumed ─────────────────────────────────────────────────────────

  group('S2C: session.resumed', () {
    test(
      // Contract C2/C5: resumption reply has sessionId, threadId, optional
      // conversationId.  Java encodes them as tstr; Dart must decode correctly
      // so the adapter can trigger thread.sync.request.
      'session_resumed__basic',
      () {
        final f = _loadFixture('session_resumed__basic');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture session_resumed__basic.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<SessionResumedMsg>());
        final resumed = msg as SessionResumedMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(resumed.sessionId, body['sessionId']);
        expect(resumed.threadId, body['threadId']);
      },
    );
  });

  // ── ack ─────────────────────────────────────────────────────────────────────

  group('S2C: ack', () {
    test(
      // Contract C7: accepted and applied are CBOR bool, not int 0/1.  Dart's
      // CborBool extractor returns null for non-bool nodes, defaulting to
      // false.  A Java encoding mismatch would silently treat the ack as
      // rejected, confusing the adapter's retry logic.
      'ack__accepted — accepted=true, applied=true',
      () {
        final f = _loadFixture('ack__accepted');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture ack__accepted.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<AckMsg>());
        final ack = msg as AckMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(ack.accepted, body['accepted']);
        expect(ack.applied, body['applied']);
        if (body.containsKey('clientItemId')) {
          expect(ack.clientItemId, body['clientItemId']);
        }
        if (f.expected.containsKey('replyTo')) {
          expect(ack.replyTo, f.expected['replyTo']);
        }
      },
    );

    test(
      // Contract C7: rejected ack has accepted=false.
      'ack__rejected — accepted=false',
      () {
        final f = _loadFixture('ack__rejected');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture ack__rejected.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<AckMsg>());
        final ack = msg as AckMsg;
        expect(ack.accepted, isFalse);
      },
    );
  });

  // ── thread.snapshot ─────────────────────────────────────────────────────────

  group('S2C: thread.snapshot', () {
    test(
      // Contract C2/C6: thread items are opaque maps with string keys; any
      // non-ASCII content in item fields (e.g. transcript) must be decoded as
      // a Dart String without garbling.
      'thread_snapshot__with_items — items list with Japanese text',
      () {
        final f = _loadFixture('thread_snapshot__with_items');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture thread_snapshot__with_items.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<ThreadSnapshotMsg>());
        final snap = msg as ThreadSnapshotMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(snap.threadId, body['threadId']);
        final expectedItems = body['items'] as List<dynamic>;
        expect(snap.items, hasLength(expectedItems.length));
        // Verify first item's id if present
        if (expectedItems.isNotEmpty) {
          final firstExpected = expectedItems[0] as Map<String, dynamic>;
          if (firstExpected.containsKey('id')) {
            expect(snap.items[0]['id'], firstExpected['id']);
          }
        }
      },
    );
  });

  // ── thread.patch ─────────────────────────────────────────────────────────────

  group('S2C: thread.patch', () {
    test(
      // Contract C2/C6: thread.patch ops list; Java encodes op strings as tstr.
      // A mismatch would cause all ops to decode as UnknownOp, breaking live
      // conversation updates for the user.
      'thread_patch__add_item_and_append_text — op type fidelity',
      () {
        final f = _loadFixture('thread_patch__add_item_and_append_text');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture thread_patch__add_item_and_append_text.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<ThreadPatchMsg>());
        final patch = msg as ThreadPatchMsg;
        expect(patch.ops, isNotEmpty);
        // At minimum the first op must be a known type (not UnknownOp)
        expect(patch.ops.first, isNot(isA<UnknownOp>()));
      },
    );

    test(
      // Contract C6: Japanese text in append_text delta must survive.
      'thread_patch__japanese_text — non-ASCII delta text',
      () {
        final f = _loadFixture('thread_patch__japanese_text');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture thread_patch__japanese_text.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<ThreadPatchMsg>());
        final patch = msg as ThreadPatchMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        final ops = body['ops'] as List<dynamic>;
        // Find the append_text op and check the delta
        for (var i = 0; i < patch.ops.length; i++) {
          final op = patch.ops[i];
          final expectedOp = ops[i] as Map<String, dynamic>;
          if (op is AppendTextOp && expectedOp['op'] == 'append_text') {
            expect(
              op.delta,
              expectedOp['delta'],
              reason: 'Japanese delta must survive CBOR round-trip',
            );
            break;
          }
        }
      },
    );
  });

  // ── assistant.audio.chunk ────────────────────────────────────────────────────

  group('S2C: assistant.audio.chunk', () {
    test(
      // Contract C1: pcm encoded by Java as CBOR bstr must be decoded by Dart
      // as CborBytes → Uint8List with exact byte equality.  Any base64 mis-
      // encoding would cause CborBytes to not match and the pcm field would
      // fall back to Uint8List(0), producing silence for the user.
      'assistant_audio_chunk__with_pcm — bstr byte equality',
      () {
        final f = _loadFixture('assistant_audio_chunk__with_pcm');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture assistant_audio_chunk__with_pcm.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<AssistantAudioChunkMsg>());
        final chunk = msg as AssistantAudioChunkMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(chunk.itemId, body['itemId']);
        expect(chunk.contentIndex, body['contentIndex']);
        // bstr field: compare byte-for-byte
        final expectedPcm = _expectedBstr(f.expected, 'body.pcm');
        expect(
          chunk.pcm,
          equals(expectedPcm),
          reason:
              'pcm bytes must match exactly; a mismatch means Java encoded '
              'bstr but Dart decoded it incorrectly (contract C1).',
        );
        expect(chunk.pcm, isA<Uint8List>());
      },
    );
  });

  // ── assistant.audio.done ─────────────────────────────────────────────────────

  group('S2C: assistant.audio.done', () {
    test(
      // Contract C2/C4: itemId tstr, contentIndex int.
      'assistant_audio_done__basic',
      () {
        final f = _loadFixture('assistant_audio_done__basic');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture assistant_audio_done__basic.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<AssistantAudioDoneMsg>());
        final done = msg as AssistantAudioDoneMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(done.itemId, body['itemId']);
        expect(done.contentIndex, body['contentIndex']);
      },
    );
  });

  // ── vad.state ───────────────────────────────────────────────────────────────

  group('S2C: vad.state', () {
    test(
      // Contract C7: isSpeaking is CBOR bool.  If Java encoded it as int 1/0
      // instead of bool true/false, Dart's CborBool extractor would return
      // null and the VAD speaking indicator would always be false.
      'vad_state__speaking — isSpeaking=true',
      () {
        final f = _loadFixture('vad_state__speaking');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture vad_state__speaking.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<VadStateMsg>());
        expect((msg as VadStateMsg).isSpeaking, isTrue);
      },
    );

    test('vad_state__silent — isSpeaking=false', () {
      final f = _loadFixture('vad_state__silent');
      if (f == null) {
        markTestSkipped(
          'Java S2C fixture vad_state__silent.cbor not yet generated.',
        );
        return;
      }

      final msg = _codec.decode(f.cbor);
      expect(msg, isA<VadStateMsg>());
      expect((msg as VadStateMsg).isSpeaking, isFalse);
    });
  });

  // ── error ────────────────────────────────────────────────────────────────────

  group('S2C: error', () {
    test(
      // Contract C2/C7: code and message are tstr; recoverable is bool.
      // replyTo is optional tstr.  An incorrectly encoded error would prevent
      // the adapter from knowing whether to close the connection.
      'error__recoverable — code, message, recoverable=true',
      () {
        final f = _loadFixture('error__recoverable');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture error__recoverable.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<ErrorMsg>());
        final err = msg as ErrorMsg;
        final body = f.expected['body'] as Map<String, dynamic>;
        expect(err.code, body['code']);
        expect(err.message, body['message']);
        expect(err.recoverable, body['recoverable']);
      },
    );

    test(
      // Contract C7: recoverable=false must be decoded as false bool, not
      // defaulted to true.  A wrong value would prevent proper connection
      // teardown after a fatal error.
      'error__unrecoverable — recoverable=false, no replyTo',
      () {
        final f = _loadFixture('error__unrecoverable');
        if (f == null) {
          markTestSkipped(
            'Java S2C fixture error__unrecoverable.cbor not yet generated.',
          );
          return;
        }

        final msg = _codec.decode(f.cbor);
        expect(msg, isA<ErrorMsg>());
        final err = msg as ErrorMsg;
        expect(err.recoverable, isFalse);
        expect(err.replyTo, isNull);
      },
    );
  });
}
